name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest]
        ocaml-compiler: [ 4.12.0 ]

    steps:
      - uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install Assembler for Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y nasm
          nasm --version

      - name: Install Assembler for MacOS
        if: runner.os == 'macOS'
        run: |
          brew install nasm
          nasm --version

      - name: Install Opam Packages
        run: |
          opam install dune utop ounit2 core shexp ppx_deriving menhir \
                       ppx_inline_test ppx_let ppx_blob

      - name: Build Code
        run: |
          eval $(opam env)
          dune build

      - name: Build Runtime
        run: gcc -c runtime.c -o runtime.o

      - name: Simple Test
        run: |
          eval $(opam env)
          dune utop <<< 'Cs164.Compile.compile_and_run "(add1 56)";;'